### ISSUE TITLE
Change scrollTop for anchors

### ISSUE THREAD

**Issue by richarddewit** [okgrow/iron-router-autoscroll#6]
I have a static header. The hash-autoscroll scrolls it to the top of the page, but I'd like it to be 50px or so lower.

Is it possible to change the offset of the scroll?

**Comment by pauldowman** [comment]
That would be a nice feature, I would happily take a PR for it. It should be a pretty simple change. Instead of 0 you could use a different value [here](https://github.com/okgrow/iron-router-autoscroll/blob/master/client/iron-router-autoscroll.js#L43), make it default to 0 and configurable [like this](https://github.com/okgrow/iron-router-autoscroll/blob/master/client/iron-router-autoscroll.js#L2).

**Comment by nlfonseca** [comment]
Nice. I'm waiting for this enhancement! :)

**Comment by deanrad** [comment]
This issue was moved to okgrow/router-autoscroll#9
